server {
    #listen 80;
    #server_name localhost;

    # Redirigir /app1 ? /app1/
    location = /app1 {
        return 308 /app1/;
    }

    # Proxy al backend .NET
    location /app1/api/ {
        rewrite ^/app1(/api/.*)$ $1 break;
        proxy_pass http://appgestionproyectos.server:80;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Servir React (SPA)
    location /app1/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /app1/index.html;
    }

    # Opcional: redirigir raíz a app1
    location = / {
        return 308 /app1/;
    }
}