# docker-compose.prod.yml
services:
  appgestionproyectos.server:
    build:
      context: .
      dockerfile: AppGestionProyectos.Server/Dockerfile
    image: appgestionproyectosserver:prod
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Default: ${CONNSTR}   # <-- cadena hacia MySQL remoto
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__ExpireMinutes: ${JWT_EXPIREMINUTES}
    expose:
      - "80"  # solo red interna docker

  web:
    build:
      context: .
      dockerfile: appgestionproyectos.client/Dockerfile  # (Caddy/Nginx que sirve React)
      args:
        # VITE_API_URL: https://onerise.es/app1/api    
        VITE_API_URL: https://localhost/app1/ 

    image: appgestionproyectosweb:prod
    restart: unless-stopped
    depends_on:
      - appgestionproyectos.server
    ports:
      - "80:80"
      - "443:443"   # http://IP_DEL_VPS
    volumes:
      # Caddyfile con las rutas
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      # build estático de app1 (lo copiamos durante el deploy)
      - ./deploy_static/app1:/usr/share/caddy/app1:ro
      # landing raíz (opcional)
      - ./deploy_static/root:/usr/share/caddy/root:ro
      # persistencia certificados
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data:
  caddy_config: